// ============================================
// ORIEMARK DIGITAL SOLUTIONS
// js/products.js — Product Data Store
// ============================================

const PRODUCTS = [
  // ---- SMARTPHONES ----
  {
    id: 1,
    name: "Samsung Galaxy S24 Ultra",
    category: "Smartphones",
    price: 820000,
    oldPrice: 950000,
    rating: 4.9,
    reviews: 312,
    Image: "<img src='/Images/Products_Images/Phones/SAMSUNG GALAXY S24.jpg' alt='Samsung Galaxy S24 Ultra' class='product-image'>",
    badge: "sale",
    tags: ["5G", "200MP Camera", "S-Pen", "AI Features"],
    description: "The ultimate Samsung flagship with a 200MP camera, built-in S-Pen, and powerful Snapdragon 8 Gen 3 processor.",
    inStock: true,
    featured: true
  },
  {
    id: 2,
    name: "iPhone 15 Pro Max",
    category: "Smartphones",
    price: 1100000,
    oldPrice: null,
    rating: 4.8,
    reviews: 245,
    Image: "<img src='/Images/Products_Images/Phones/IPHONE 15 PRO MAX.webp' alt='iPhone 15 Pro Max' class='product-image'>",
    badge: "new",
    tags: ["A17 Pro", "Titanium", "USB-C", "48MP"],
    description: "Apple's most powerful iPhone with titanium design, A17 Pro chip, and a 48MP Main camera with 5x optical zoom.",
    inStock: true,
    featured: true
  },
  {
    id: 3,
    name: "Tecno Phantom X2 Pro",
    category: "Smartphones",
    price: 320000,
    oldPrice: 360000,
    rating: 4.5,
    reviews: 89,
    emoji: "📱",
    Image: "<img src='/Images/Products_Images/Phones/Tecno Phantom X2 Pro.png' alt='Tecno Phantom X2 Pro' class='product-image'>",
    badge: "sale",
    tags: ["5G", "64MP", "Pop-Up Camera"],
    description: "Tecno's flagship with a retractable portrait lens, 6.8-inch AMOLED display, and all-day battery life.",
    inStock: true,
    featured: false
  },
  {
    id: 4,
    name: "Google Pixel 8 Pro",
    category: "Smartphones",
    price: 750000,
    oldPrice: null,
    rating: 4.7,
    reviews: 132,
    emoji: "📱",
    Image: "<img src='/Images/Products_Images/Phones/Google Pixel 8 Pro.png' alt='Google Pixel 8 Pro' class='product-image'>",
    badge: null,
    tags: ["AI Camera", "Tensor G3", "7 yrs updates"],
    description: "Pure Android experience with Tensor G3 chip, best-in-class computational photography, and 7 years of OS updates.",
    inStock: true,
    featured: false
  },
  {
    id: 5,
    name: "Infinix Zero 30 5G",
    category: "Smartphones",
    price: 185000,
    oldPrice: 210000,
    rating: 4.4,
    reviews: 76,
    emoji: "📱",
    Image: "<img src='/Images/Products_Images/Phones/Infinix Zero 30 5G.png' alt='Infinix Zero 30 5G' class='product-image'>",
    badge: "sale",
    tags: ["5G", "144Hz AMOLED", "108MP"],
    description: "Budget flagship with a 108MP camera, 144Hz curved AMOLED screen, and 5G connectivity at an unbeatable price.",
    inStock: true,
    featured: false
  },

  // ---- SMARTWATCHES ----
  {
    id: 6,
    name: "Apple Watch Series 9",
    category: "Smartwatches",
    price: 430000,
    oldPrice: 480000,
    rating: 4.9,
    reviews: 198,
    emoji: "⌚",
    Image: "<img src='/Images/Products_Images/Watches/Apple Watch Series 9.png' alt='Apple Watch Series 9' class='product-image'>",
    badge: "sale",
    tags: ["Always-On", "ECG", "S9 Chip", "GPS"],
    description: "The smartest Apple Watch yet with the new S9 chip, brighter display, and the revolutionary Double Tap gesture.",
    inStock: true,
    featured: true
  },
  {
    id: 7,
    name: "Samsung Galaxy Watch 6 Classic",
    category: "Smartwatches",
    price: 285000,
    oldPrice: null,
    rating: 4.6,
    reviews: 144,
    emoji: "⌚",
    Image: "<img src='/Images/Products_Images/Watches/Samsung Galaxy Watch 6 Classic.png' alt='Samsung Galaxy Watch 6 Classic' class='product-image'>",
    badge: null,
    tags: ["Rotating Bezel", "BioActive", "Sapphire Glass"],
    description: "Premium smartwatch with iconic rotating bezel, comprehensive health sensors, and premium sapphire crystal glass.",
    inStock: true,
    featured: false
  },
  {
    id: 8,
    name: "Garmin Forerunner 265",
    category: "Smartwatches",
    price: 350000,
    oldPrice: null,
    rating: 4.7,
    reviews: 77,
    emoji: "⌚",
    Image: "<img src='/Images/Products_Images/Watches/Garmin Forerunner 265.png' alt='Garmin Forerunner 265' class='product-image'>",
    badge: "new",
    tags: ["AMOLED", "Training Readiness", "GPS"],
    description: "Garmin's top running watch with AMOLED display, advanced training analytics, and up to 15 days battery life.",
    inStock: true,
    featured: false
  },
  {
    id: 9,
    name: "Huawei Watch GT 4",
    category: "Smartwatches",
    price: 195000,
    oldPrice: 225000,
    rating: 4.5,
    reviews: 91,
    emoji: "⌚",
    Image: "<img src='/Images/Products_Images/Watches/Huawei Watch GT 4.png' alt='Huawei Watch GT 4' class='product-image'>",
    badge: "sale",
    tags: ["2-Week Battery", "ECG", "SpO2"],
    description: "Elegant smartwatch with exceptional 2-week battery life, precise health monitoring, and premium octagonal design.",
    inStock: true,
    featured: false
  },

  // ---- AUDIO ----
  {
    id: 10,
    name: "AirPods Pro (2nd Gen)",
    category: "Audio",
    price: 195000,
    oldPrice: 220000,
    rating: 4.8,
    reviews: 421,
    emoji: "🎧",
    Image: "<img src='/Images/Products_Images/Audios/AirPods Pro (2nd Gen).png' alt='AirPods Pro (2nd Gen)' class='product-image'>",
    badge: "sale",
    tags: ["ANC", "Spatial Audio", "H2 Chip"],
    description: "Apple's best earbuds with up to 2x more active noise cancellation, Adaptive Audio, and Conversation Awareness.",
    inStock: true,
    featured: true
  },
  {
    id: 11,
    name: "Sony WH-1000XM5",
    category: "Audio",
    price: 230000,
    oldPrice: null,
    rating: 4.9,
    reviews: 356,
    emoji: "🎧",
    Image: "<img src='/Images/Products_Images/Audios/Sony WH-1000XM5.png' alt='Sony WH-1000XM5' class='product-image'>",
    badge: "hot",
    tags: ["Industry-leading ANC", "30hr battery", "LDAC"],
    description: "The gold standard in wireless noise-canceling headphones with 8 microphones, 30-hour battery, and ultra-premium sound.",
    inStock: true,
    featured: false
  },
  {
    id: 12,
    name: "JBL Charge 5",
    category: "Audio",
    price: 95000,
    oldPrice: 110000,
    rating: 4.6,
    reviews: 203,
    emoji: "🔊",
    Image: "<img src='/Images/Products_Images/Audios/JBL Charge 5.png' alt='JBL Charge 5' class='product-image'>",
    badge: "sale",
    tags: ["IP67 Waterproof", "20hr Playtime", "PowerBank"],
    description: "Portable Bluetooth speaker with IP67 waterproofing, massive 7500mAh battery that can charge your devices.",
    inStock: true,
    featured: false
  },
  {
    id: 13,
    name: "Samsung Galaxy Buds2 Pro",
    category: "Audio",
    price: 145000,
    oldPrice: 165000,
    rating: 4.5,
    reviews: 167,
    emoji: "🎧",
    Image: "<img src='/Images/Products_Images/Audios/Samsung Galaxy Buds2 Pro.png' alt='Samsung Galaxy Buds2 Pro' class='product-image'>",
    badge: "sale",
    tags: ["360° Audio", "ANC", "Hi-Fi Sound"],
    description: "Samsung's premium buds with 360° Audio, Hi-Fi sound, and comfortable ergonomic design for all-day wear.",
    inStock: true,
    featured: false
  },

  // ---- LAPTOPS ----
  {
    id: 14,
    name: "MacBook Air M3 (15-inch)",
    category: "Laptops",
    price: 1450000,
    oldPrice: null,
    rating: 4.9,
    reviews: 187,
    emoji: "💻",
    Image: "<img src='/Images/Products_Images/Laptops/MacBook Air M3 (15-inch).png' alt='MacBook Air M3 (15-inch)' class='product-image'>",
    badge: "new",
    tags: ["M3 Chip", "18hr Battery", "Liquid Retina"],
    description: "Apple's supercharged thin and light laptop with the powerful M3 chip, 18-hour battery, and fanless design.",
    inStock: true,
    featured: true
  },
  {
    id: 15,
    name: "Dell XPS 15 (2024)",
    category: "Laptops",
    price: 1200000,
    oldPrice: 1380000,
    rating: 4.7,
    reviews: 98,
    emoji: "💻",
    Image: "<img src='/Images/Products_Images/Laptops/Dell XPS 15 (2024).png' alt='Dell XPS 15 (2024)' class='product-image'>",
    badge: "sale",
    tags: ["Intel i9", "4K OLED", "RTX 4060"],
    description: "Dell's premium 15-inch laptop with stunning 4K OLED display, Intel 14th Gen processor, and NVIDIA RTX graphics.",
    inStock: true,
    featured: false
  },
  {
    id: 16,
    name: "Lenovo ThinkPad X1 Carbon",
    category: "Laptops",
    price: 980000,
    oldPrice: null,
    rating: 4.6,
    reviews: 76,
    emoji: "💻",
    Image: "<img src='/Images/Products_Images/Laptops/Lenovo ThinkPad X1 Carbon.png' alt='Lenovo ThinkPad X1 Carbon' class='product-image'>",
    badge: null,
    tags: ["Ultra-light", "Intel vPro", "MIL-SPEC"],
    description: "The business-class ultra-portable with military-grade durability, legendary ThinkPad keyboard, and all-day battery.",
    inStock: true,
    featured: false
  },
  {
    id: 17,
    name: "HP Spectre x360 14",
    category: "Laptops",
    price: 1050000,
    oldPrice: 1180000,
    rating: 4.6,
    reviews: 63,
    emoji: "💻",
    Image: "<img src='/Images/Products_Images/Laptops/HP Spectre x360 14.png' alt='HP Spectre x360 14' class='product-image'>",
    badge: "sale",
    tags: ["2-in-1", "OLED Touch", "Intel Evo"],
    description: "HP's stunning 2-in-1 convertible laptop with OLED touchscreen, Intel Evo platform, and gem-cut premium design.",
    inStock: false,
    featured: false
  },

  // ---- ACCESSORIES ----
  {
    id: 18,
    name: "Anker 65W GaN Prime Charger",
    category: "Accessories",
    price: 35000,
    oldPrice: 42000,
    rating: 4.8,
    reviews: 312,
    emoji: "🔌",
    Image: "<img src='/Images/Products_Images/Accessories/Anker 65W GaN Prime Charger.png' alt='Anker 65W GaN Prime Charger' class='product-image'>",
    badge: "sale",
    tags: ["GaN Technology", "3 Ports", "PowerIQ 4.0"],
    description: "Charge 3 devices simultaneously with GaN technology. Compact design packs laptop-level power in pocket size.",
    inStock: true,
    featured: false
  },
  {
    id: 19,
    name: "Samsung 25000mAh Power Bank",
    category: "Accessories",
    price: 78000,
    oldPrice: null,
    rating: 4.5,
    reviews: 167,
    emoji: "🔋",
    Image: "<img src='/Images/Products_Images/Accessories/Samsung 25000mAh Power Bank.png' alt='Samsung 25000mAh Power Bank' class='product-image'>",
    badge: "new",
    tags: ["45W Fast Charge", "USB-C PD", "LCD Display"],
    description: "High-capacity power bank with 45W fast charging, LCD battery display, and ability to charge laptops on the go.",
    inStock: true,
    featured: false
  },
  {
    id: 20,
    name: "Logitech MX Master 3S",
    category: "Accessories",
    price: 98000,
    oldPrice: 110000,
    rating: 4.9,
    reviews: 289,
    emoji: "🖱️",
    Image: "<img src='/Images/Products_Images/Accessories/Logitec Mouse.jpg' alt='Logitech MX Master 3S' class='product-image'>",
    badge: "sale",
    tags: ["8K DPI", "Quiet Clicks", "Multi-Device"],
    description: "The ultimate productivity mouse with ultra-precise tracking, near-silent clicks, and ergonomic sculpted design.",
    inStock: true,
    featured: false
  },

  // ---- CAMERAS ----
  {
    id: 21,
    name: "Canon EOS R6 Mark II",
    category: "Cameras",
    price: 1850000,
    oldPrice: null,
    rating: 4.8,
    reviews: 156,
    emoji: "📷",
    Image: "<img src='/Images/Products_Images/Cameras/Canon EOS R6 Mark II.png' alt='Canon EOS R6 Mark II' class='product-image'>",
    badge: "new",
    tags: ["24MP", "4K 60p", "IBIS", "Eye AF"],
    description: "Professional mirrorless camera with 24MP full-frame sensor, 4K 60p video, and advanced autofocus for creators.",
    inStock: true,
    featured: true
  },
  {
    id: 22,
    name: "Sony Alpha a7 IV",
    category: "Cameras",
    price: 1650000,
    oldPrice: 1850000,
    rating: 4.9,
    reviews: 203,
    emoji: "📷",
    Image: "<img src='/Images/Products_Images/Cameras/Sony Alpha a7 IV.png' alt='Sony Alpha a7 IV' class='product-image'>",
    badge: "sale",
    tags: ["33MP", "4K 60p", "Real-time AF", "5-axis IBIS"],
    description: "Full-frame mirrorless powerhouse with 33MP sensor, 4K 60p video, and exceptional autofocus tracking.",
    inStock: true,
    featured: false
  },
  {
    id: 23,
    name: "DJI Pocket 3",
    category: "Cameras",
    price: 285000,
    oldPrice: null,
    rating: 4.7,
    reviews: 89,
    emoji: "📷",
    Image: "<img src='/Images/Products_Images/Cameras/DJI Pocket 3.png' alt='DJI Pocket 3' class='product-image'>",
    badge: "new",
    tags: ["4K 120fps", "3-axis Gimbal", "AI Tracking", "Pocket Size"],
    description: "Compact 3-axis gimbal camera with 4K 120fps video, AI subject tracking, and professional stabilization.",
    inStock: true,
    featured: false
  },
  {
    id: 24,
    name: "GoPro HERO12 Silver",
    category: "Cameras",
    price: 195000,
    oldPrice: 220000,
    rating: 4.6,
    reviews: 134,
    emoji: "📷",
    Image: "<img src='/Images/Products_Images/Cameras/GoPro HERO12 Silver.png' alt='GoPro HERO12 Silver' class='product-image'>",
    badge: "sale",
    tags: ["5.3K 60fps", "HyperSmooth 6.0", "Waterproof", "TimeWarp"],
    description: "Rugged action camera with 5.3K 60fps video, HyperSmooth 6.0 stabilization, and waterproof design for adventure.",
    inStock: true,
    featured: false
  },

  // ---- SMART TOYS ----
  {
    id: 25,
    name: "Robo-Ally Interactive Robot",
    category: "Children's Toys",
    price: 85000,
    oldPrice: 100000,
    rating: 4.6,
    reviews: 58,
    emoji: "🤖",
    Image: "<img src='/Images/Products_Images/Children's_Toy/Robo-Ally Interactive Robot.png' alt='Robo-Ally Interactive Robot' class='product-image'>",
    badge: "sale",
    tags: ["Voice Control", "App Control", "Educational", "Rechargeable"],
    description: "Interactive robot companion with voice recognition, app control, and educational features. Perfect for kids aged 6+.",
    inStock: true,
    featured: true
  },
  {
    id: 26,
    name: "Smart Building Blocks Pro",
    category: "Children's Toys",
    price: 45000,
    oldPrice: null,
    rating: 4.5,
    reviews: 42,
    emoji: "🧱",
    Image: "<img src='/Images/Products_Images/Children's_Toys/Smart Building Blocks Pro.png' alt='Smart Building Blocks Pro' class='product-image'>",
    badge: "new",
    tags: ["STEM Learning", "App Guided", "500+ Pieces", "Ages 4+"],
    description: "Creative building blocks with app-guided tutorials. Enhances problem-solving skills and creativity in children.",
    inStock: true,
    featured: false
  },
  {
    id: 27,
    name: "Drone Explorer Mini",
    category: "Children's Toys",
    price: 65000,
    oldPrice: 75000,
    rating: 4.7,
    reviews: 76,
    emoji: "🚁",
    Image: "<img src='/Images/Products_Images/Children's_Toys/Drone Explorer Mini.png' alt='Drone Explorer Mini' class='product-image'>",
    badge: "sale",
    tags: ["GPS", "HD Camera", "30min Flight", "Beginner Friendly"],
    description: "Kid-friendly drone with GPS, HD camera, and 30-minute flight time. Easy to fly with auto-return home feature.",
    inStock: true,
    featured: false
  },
  {
    id: 28,
    name: "Smart Learning Tablet Pro",
    category: "Children's Toys",
    price: 55000,
    oldPrice: 65000,
    rating: 4.8,
    reviews: 89,
    emoji: "📲",
    Image: "<img src='/Images/Products_Images/Children's_Toys/Smart Learning Tablet Pro.png' alt='Smart Learning Tablet Pro' class='product-image'>",
    badge: "sale",
    tags: ["Educational Games", "Parental Control", "Ages 3-10", "Durable"],
    description: "Educational tablet designed for children with parental controls, age-appropriate games, and durable kid-proof case.",
    inStock: true,
    featured: false
  }
];

// ---- CATEGORIES ----
const CATEGORIES = ["All", "Smartphones", "Smartwatches", "Audio", "Laptops", "Accessories", "Cameras", "Children's Toys"];

// ---- EXPORT ----
if (typeof module !== 'undefined') module.exports = { PRODUCTS, CATEGORIES };
